"""
Shopee Affiliate Bot — Dashboard (Streamlit Community Cloud version)

Supports file upload for Excel data generated by the local pipeline.
"""

import io
import json
from datetime import datetime
from pathlib import Path

import pandas as pd
import plotly.express as px
import streamlit as st

# ── Page config ───────────────────────────────────────────────────────────────
st.set_page_config(
    page_title="Shopee Affiliate Bot",
    page_icon="🛒",
    layout="wide",
    initial_sidebar_state="expanded",
)

STATUS_COLORS = {
    "pendente": "#FFA500",
    "publicado_tiktok": "#00CC44",
    "publicado_shopee": "#00AAFF",
    "fila_manual": "#9B59B6",
    "falhou_tiktok": "#FF3333",
    "falhou_shopee": "#FF6666",
}

EXCEL_COLUMNS = [
    "produto", "link_original", "link_afiliado",
    "comissao_novo", "comissao_atual",
    "overlay", "legenda", "hashtags", "estrategia",
    "status_agendamento", "data_publicacao",
]


# ── Session state ─────────────────────────────────────────────────────────────

def _get_df() -> pd.DataFrame:
    return st.session_state.get("df", pd.DataFrame())


def _set_df(df: pd.DataFrame):
    st.session_state["df"] = df


# ── Sidebar ───────────────────────────────────────────────────────────────────

def render_sidebar():
    with st.sidebar:
        st.image("https://img.icons8.com/color/96/shopee.png", width=60)
        st.title("Shopee Affiliate Bot")
        st.markdown("---")

        st.subheader("📂 Carregar Dados")
        uploaded = st.file_uploader(
            "Upload do output.xlsx",
            type=["xlsx"],
            help="Gere o arquivo rodando 'python main.py' no seu PC e faça upload aqui.",
        )
        if uploaded:
            try:
                df = pd.read_excel(uploaded, engine="openpyxl")
                _set_df(df)
                st.success(f"{len(df)} produtos carregados!")
            except Exception as e:
                st.error(f"Erro ao ler arquivo: {e}")

        st.markdown("---")

        df = _get_df()
        if not df.empty:
            # Download button
            buf = io.BytesIO()
            df.to_excel(buf, index=False, engine="openpyxl")
            st.download_button(
                label="⬇ Baixar Excel Atualizado",
                data=buf.getvalue(),
                file_name=f"shopee_afiliados_{datetime.now().strftime('%Y%m%d_%H%M')}.xlsx",
                mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                use_container_width=True,
            )

        st.markdown("---")
        st.subheader("📋 Como usar")
        st.markdown("""
1. Rode no seu PC:
   ```
   python main.py
   ```
2. Faça upload do arquivo:
   ```
   data/output.xlsx
   ```
3. Visualize os dados aqui
4. Baixe o Excel atualizado
        """)
        st.caption(f"Atualizado: {datetime.now().strftime('%H:%M:%S')}")


# ── KPIs ──────────────────────────────────────────────────────────────────────

def render_kpis(df: pd.DataFrame):
    st.subheader("Resumo")
    c1, c2, c3, c4, c5, c6 = st.columns(6)

    total = len(df)
    ai_ok = len(df[df["overlay"].str.len() > 5]) if "overlay" in df.columns and total > 0 else 0
    published = len(df[df["status_agendamento"].str.startswith("publicado", na=False)]) if "status_agendamento" in df.columns else 0
    pending = len(df[df["status_agendamento"] == "pendente"]) if "status_agendamento" in df.columns else 0
    avg_new = df["comissao_novo"].mean() if "comissao_novo" in df.columns and total > 0 else 0
    avg_existing = df["comissao_atual"].mean() if "comissao_atual" in df.columns and total > 0 else 0

    c1.metric("Total Produtos", total)
    c2.metric("Copy Gerado", ai_ok)
    c3.metric("Publicados", published)
    c4.metric("Pendentes", pending)
    c5.metric("Comissão Média Novo", f"{avg_new:.1f}%")
    c6.metric("Comissão Média Atual", f"{avg_existing:.1f}%")


# ── Products Table ────────────────────────────────────────────────────────────

def render_products_table(df: pd.DataFrame):
    st.subheader("Produtos")

    if df.empty:
        st.info("Nenhum dado carregado. Faça upload do output.xlsx na barra lateral.")
        return

    col1, col2 = st.columns(2)
    with col1:
        status_options = ["Todos"] + sorted(df["status_agendamento"].dropna().unique().tolist()) if "status_agendamento" in df.columns else ["Todos"]
        selected_status = st.selectbox("Filtrar por status", status_options)
    with col2:
        search = st.text_input("Buscar produto", placeholder="Digite o nome...")

    filtered = df.copy()
    if selected_status != "Todos" and "status_agendamento" in filtered.columns:
        filtered = filtered[filtered["status_agendamento"] == selected_status]
    if search and "produto" in filtered.columns:
        filtered = filtered[filtered["produto"].str.contains(search, case=False, na=False)]

    display_cols = [c for c in ["produto", "comissao_novo", "comissao_atual", "overlay", "hashtags", "status_agendamento", "data_publicacao"] if c in filtered.columns]

    def _color_status(val):
        color = STATUS_COLORS.get(str(val), "#FFFFFF")
        return f"background-color: {color}22; color: {color}; font-weight: bold;"

    styled = filtered[display_cols].style.applymap(
        _color_status, subset=["status_agendamento"]
    ) if "status_agendamento" in display_cols else filtered[display_cols].style

    st.dataframe(styled, use_container_width=True, height=400)
    st.caption(f"Mostrando {len(filtered)} de {len(df)} produtos")


# ── Copy Viewer ───────────────────────────────────────────────────────────────

def render_copy_viewer(df: pd.DataFrame):
    if df.empty:
        return

    st.subheader("Copy para Postagem")
    st.info("Copie o conteúdo abaixo para usar nos seus vídeos.")

    pending = df[df.get("status_agendamento", pd.Series()) == "pendente"] if "status_agendamento" in df.columns else df
    if pending.empty:
        st.success("Todos os produtos já foram postados!")
        return

    for _, row in pending.head(10).iterrows():
        with st.expander(f"📦 {row.get('produto', 'Produto')} — Comissão: {row.get('comissao_novo', 0):.1f}%"):
            col1, col2 = st.columns(2)
            with col1:
                st.markdown(f"**🎬 Overlay (tela do vídeo):**")
                st.code(row.get("overlay", ""), language=None)
                st.markdown(f"**#️⃣ Hashtags:**")
                st.code(row.get("hashtags", ""), language=None)
                st.markdown(f"**🔗 Link Afiliado:**")
                st.code(row.get("link_afiliado", ""), language=None)
            with col2:
                st.markdown(f"**📝 Legenda completa:**")
                st.text_area(
                    "Copiar legenda",
                    row.get("legenda", ""),
                    height=200,
                    key=f"leg_{row.get('link_original', '')}",
                )
            st.markdown(f"*Estratégia: {row.get('estrategia', '')}*")


# ── Charts ────────────────────────────────────────────────────────────────────

def render_charts(df: pd.DataFrame):
    if df.empty:
        return

    st.subheader("Análise")
    col1, col2 = st.columns(2)

    with col1:
        if "status_agendamento" in df.columns:
            counts = df["status_agendamento"].value_counts().reset_index()
            counts.columns = ["Status", "Quantidade"]
            fig = px.bar(
                counts, x="Status", y="Quantidade",
                title="Produtos por Status",
                color="Status",
                color_discrete_map={k: v for k, v in STATUS_COLORS.items()},
            )
            fig.update_layout(showlegend=False, height=300)
            st.plotly_chart(fig, use_container_width=True)

    with col2:
        if "comissao_novo" in df.columns:
            fig2 = px.histogram(
                df, x="comissao_novo", nbins=20,
                title="Distribuição de Comissão (Novos Compradores)",
                labels={"comissao_novo": "Comissão (%)"},
                color_discrete_sequence=["#FF6B35"],
            )
            fig2.update_layout(height=300)
            st.plotly_chart(fig2, use_container_width=True)


# ── Main ──────────────────────────────────────────────────────────────────────

def main():
    render_sidebar()

    st.title("🛒 Shopee Affiliate Bot — Dashboard")
    st.markdown("Visualize produtos, copy gerado por IA e status de postagem.")
    st.markdown("---")

    df = _get_df()

    render_kpis(df)
    st.markdown("---")
    render_products_table(df)
    st.markdown("---")
    render_copy_viewer(df)
    st.markdown("---")
    render_charts(df)


if __name__ == "__main__":
    main()
